language: go
sudo: false
go:
- 1.10x
before_install:
- go get github.com/kurrik/oauth1a
- go get github.com/kurrik/twittergo
jobs:
  include:
  - script: make all
    deploy:
      provider: releases
      skip_cleanup: true
      on:
        tags: true
env:
  global:
  - secure: SIXpdf0T0KgZ/7p3dRE7KM8waFFIV3osIBCxQ9FgaLH8/FaX2/LLbjDsZlYODyQu5rgU8eEIabTew/NXaOx1rdm+hPlhQHS0Qar3D6Tf2sTpjskpqSSBFXlsDl2Cj6aLv7nSfJEb/jrU1FjXMut4c753x4h6fJkuNzb6aOdiWG0znxjPI7WHxGnqucQdVxoHffi/w0+x2VfkLWDP9ydLNBcjlBKaTwPFoYepIPygf12QT0H4bNFWZrKaUGUZa3xjeAQ42BicGFRnjoCf3JJqQmb+THgLgevpaliagP9TpMpFUltaUxwuGJh703MYugPKYqAvXiqE25UhaLEj7BuODHUV2ZyqSsUXrHFpn5UszELYDUs8dQx5Fdb5HPshkBvXKSrE9nUTkVfJ7g/W7FvEQSbK2wp9EDZjrnYdPYGNvm9XOVedKP1KzAhS4QntmHDvZ4/cGgLjIv6N3QKZrb+zMSAo0Mo1ms4vF/dN1L3gbo350Bqw500HSK/J+QKik0PkTDBxfpRNI9KXHXzQRf37QCjMaxOYHHzCBYXNPkYe8W8vrMane9t5as5U9dZdjHHjGshb+6YzVSuq1h4p+B/nL9ZmHAK7G/eqWD9r4QKSWsdJ8TMJy/XoLKDiGRu/MBgg2hfCuUpjsC8jsE24e4b3iHakj0ebkvdYTLucZoKt24k=
  - secure: 0jytZukxmGxugJncGoCwTbYrE3OHjbONvzPwczjNlv3NfF6jKrZPP1ZV0MDaX0bYurwYBDRqjTHvuSL1QFgouDSGg/mULb5w+nkIx84Lws1OD2yzaF9jroD2fF+3meHUtUjhRAWKcaEvCgmlMZqGBerDu2R4hC5G3bZFFBBPSwKKqevJFGXOx37tUuKw2A9/+h5xd4sebY4D0mq+7aKvlnszJS5gj+xrw62wva+BV7hH9oG8dMHnpIpDtrHB8NRlUAP0GXOFSnOObLE1oAKfvGm3YVidG1h2cwpbIkkPBoCXt2ElVq9wpp3xjHmbACi92H0msu1t2VL2gShzETkhmsmpW7c6OYQ67T0TSji5Sf4T0n6K8Rpw9fde2vWkRM9CTfZL7wvePshRiNHUcRiZGqtzo9Ij0wiWxwck/lXU2zSeuISBrVAr1uFLsFj5Ra/DGYzAqSRcoys9uqLh/y86NtnMrXE+Q1nvP34NVNwGM33yoe/BTIgZFjwvNxCJbzI2Wf7LiBBtMWRuvIS8SFh5AH804VDTe/f5TCvUxaJH19mlUJXd0r2yQUUy98ZKp4p5OlvSRLFqgQLVGGqmAjhel3Zjc+Q0tuKouOESPFJ4FNgKETbNU+oPZAl+wBkkYHamCaCX51K6vesQpaXhpWR/N+ugaenghwQRpXkhKnubWjI=
