language: go
sudo: false
go:
- 1.11
before_install:
- go get github.com/kurrik/oauth1a
- go get github.com/kurrik/twittergo
script:
- make
deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
  env:
    global:
      - secure: wHMdfUvIILaIw245NSa1ne2JMvo4Hp2pJYTeqr0QO24objNegaI/i5C2yOwww5yNlnSNAMVIp1r1ep60NKBbKcmoLFKHgxlkEtUbZ3uOBGkNCQ3NoaebXYQmgq/Y5oI21sZbJHq3/l0uURBBCMNPOCfS/MdqOFACsSaTYRt40QlNdwWGgrwrPaZ8Nxnspp5az/t8hsKcZVHZSCkZzWoF+kzYAuTzFF7F1m+wRj7kM1JZ/Wyjq0PFHoyLzWniRAnBFOhLcMwM2darie+V6ugOsTHJoLDhaZ4IEyepFDZr0P+1xoTQ4V1quxaGfLNtkwb7qOnygB8jiSZSggKD9Nd4dpNPtqHQbYQiw1y0Jm1ET3BSpKxYoSxQEoQyyh++qQ8fyELTawU0Djx1P3tIZE/Ck6j2fYdqWC6Nk49hwQIBoXdbbvYws4ILbcXe9B+mHcntUch5MlPvezm6KfbPhkzXBgSRz9m52CRIJXy7rcrC2xlx7b8v9FRxJ4nfsyHvlPKhyRf4QkEXZ2j8udF6zvHptFdQR+7wqZnJMKUIi0arGyYBbeLNsXlYCsz4DywmRVV2TbAuNPHoOV7X2FFC+vrcBJ2JxD52wWnqhH1zPJHGCEIGiptQ7o3Rf44kABq/eLaKSw6YzDXtvWFLArz6p+uUMIIj4pFVDtH7GF9vfqdXiKo=
      - secure: qYp/IhF8HR/XHq0pObjKKzqydkrAXGyth00gOkqlPDYAbnCx8uL6RkGfZaFozUb67mN0toKphvtVPge0UJSqYCwcwHZSXu6NFzBhtzizYg12KjIYp8aOy/CxuXVhUxqK31CfnRvmY4jr8r1/XuWDSMeUahlAAcPGMsh0S0kaYzevL1AWnyKHz5SQOwfNQPh+yYEs9qFWP76iUhih9Kk3LnbmpfCJHr6q+7w+Ed3J1HRIQ6lS9Dajm45q3T+3WIqb13yv+C9AGk8Q2RpRfAPsRgEUCIFm/+n93a3NiDr2jYRnhpjvYv36bm6UJ2emU7xsUwcDCSLMgc4ExKHbSw51yqIzRHp6gpwRXW7r/f2gxsWR+aS60T+m+z/gycBDHr2svR959WQ9fg803RHXZj01j/CCZztEJYoebm0cjWb7OLtvUHTzB0miye5OT1aDJ2lJaByTJTLGSIiZfY+DfYSq8TRmY1qE9M9F0Av8Hcbl5VX2uRiAHDu+x+76NqcX7MgMTQuogBgN10RCexmzQ71XDzDFSUL2bC8jM1RVHxRnvOu2vwTcHlr6hLH1kLXqz/27YFpg3iGWF6dMzD/QpccZ+Z7+qgBdCirkWfEVnAJ6Fgy+3TBNUVZd6bWaJ3WNsgOpHTPLKbcb5+8phHotlVuMzOdGshLh7xOVESkmDpmfm3w=
