language: go
sudo: false
go:
- 1.10x
before_install:
- go get github.com/kurrik/oauth1a
- go get github.com/kurrik/twittergo
jobs:
  include:
    - script: make all
      deploy:
        provider: releases
        skip_cleanup: true
        on:
          tags: true
        env:
          global:
            - secure: SuTZp/ua92DElQpdUF6C80BrVcXrNvJgHvt1kVSt8LNjgX2uUQzFgLepFlTI1Kki//X1YWqr7ISYfzrouNoing4k16mPvT0yE1oMbs6mmtQ9ezKRgZOkuBAa7u1cIWpq3hnEyDucEPVryJCEfqiQaMsGFzArmB7jerB5pUb5YTzou10S3uLSWjwECOnqHQV6siGolMFNqP2SxZLzUAdfsaLZaI3pziN553iG5AsJoYZ+sjOBiKNufT6E/5d7VGol101JD0xVWlhzIYlGV0vE9uB825tfsqIQvtIRky5NmCniL7AZe8CUdW/wdGHexZ/920PcD8/e0nX3VpO2B5/obqF2cZbEGdfkXq54kb1DdGYBZ68LnhEC3fzgUZYLnhq35XgWQBWbL9uiy6UPQuTweg4LBAdGMgJDu5bnWGyjownmNn9BpQleSwCkA7Fl/QnN6w05P75KYoX2KpKLa3JyzI+asV3DYIa5gGKt0oPPa5PiosNR64T9cWuMBOd4HEr15ZNrLzbHW5b8jFacbaUwndVJNQ166GQrsbBAdeiO4fgpkdX0YzK88vWcAUz5O06/8epeoIO5iz1wQbSS6IbwlHoxpSaZbqQ+GqNoKJ1d/OAve+EhGx9v/LwrayT8bKUj+v8YC7JAE2tPAmXeR4Q/Bf7hbsSEKKgBwi+He7zUqkA=
            - secure: PkiRmx5V905rN2thcrlRVFASU1hDx1D+ODpAPdWR1ew0XDuqmKDgB5cqiFsg3mlFIuuxadLVS7p0TByXjc6kzKfvbnmfOStGfW/md2QKiil45dz9rxVfYhxHZn0IiAqB2MZAYIT9sMmr2pRHtYw6Lu+lJQlUVuC5R2QI/41mGOvfc02CEXTDboDX854cdmHxqgvIvfAO89ny7RhZKBzmYaipUA3oDelWG0KNqGazx/BaGHUM6SDePDMaYLVsnIb8+qi3cIRkz6FklEVmosXp3UXbdMkte8gW4MUUUykT9kJ9nVXn/ohz610M98/Q5GXpipPtf9klqJ1REAAmS7PwRTLuG99i2zrh/X9E5faKg3tpizYeVDbMzjQmn0tUKt+SVQUEI9t9s45BcPw+cCBccskKuzkdSCI8xxUqJi5BvJJjy/bdWoGKpWtWGKOWhCuDbZikkpDnhCxN2cciQJZQ2XWVVitdXqvaEkkKVkXndfiEe0TRH9Xvo3Ij2/S71tr1m3hSTfWxsDf6DdIC3YxCVpFiOP5zLQgnOJU4ubNyLF2/nTU1Xh65rSA1PkVVB5dOAPDlUaWkQWIWpI6L6AnEjdJfhL/IbKQztXH4TWrXpG/8JpWUZD9+7XNveLycwQ5mumFiJT7EOJfZMjtcC6r40x35AYXQgmfylgYZtzgoRZM=
